### PR TITLE
Updated readme.md ("But is this against TOS ?")

### PR DESCRIPTION
**Pull request by Cyklon3000**
[README.MD](https://github.com/DvorakDwarf/Infinite-Storage-Glitch/blob/master/README.md) now includes information about a [specific YouTube policy violation](https://support.google.com/youtube/answer/2801973?hl=en).
Spam can lead to videos or channels being taken offline when YouTube notices the waste of resources on unwanted cloud storage that does not bring in advertising revenue.

**Note**: I am not a layer nor am I involved in YouTubes decisions when it comes to taking action against policy violations.

### CODE REVIEW

**Comment by danya02** [comment]
According to the linked YouTube page, "video spam" includes:

> Autogenerated content that computers post without regard for quality or viewer experience.

which in my opinion prohibits using YT videos as a personal file storage solution.
I recommend adding this link to the README and making it more explicit that this particular usage is prohibited.

It doesn't say that you're not allowed to upload videos like this at all, though.
I suggest shifting the focus of this project from "now you don't have to pay for cloud storage" to "now you can put supplementary material next to your videos".
Then, a video creator could say "if you'd like to see the code I typed in this video, use this program on this unlisted video to download it", which is a much more viewer-focused approach.

**Comment by danya02** [comment]
And now for something completely different: #24.

**Comment by DvorakDwarf** [comment]
Very minor change that makes the README sound more sanitized. I am not sure if I am blind but I don't see the "autogenerated" quote on the linked page. Using the program to link code or files with videos is a neat idea and I will mention it in the README

**Comment by wbarnha** [comment]
Disclaimer: I am not a lawyer.

I was curious about the ToS situation as well, and I looked over [community guidelines on Video Spam](https://support.google.com/youtube/answer/2801973?hl=en#zippy=%2Cvideo-spam):


The following types of content are not allowed on YouTube. Keep in mind this list isn't a complete list.

> Video Spam
>
> The following types of content are not allowed on YouTube. Keep in mind this list isn't a complete list.
>
>    ... omitting other clauses ...
    **Autogenerated content that computers post without regard for quality or viewer experience.**

I think this could be considered autogenerated content, so maybe a note could be added in the README that use of this _could_ be considered a violation of community guidelines?

**Comment by DvorakDwarf** [comment]
Merged and included links

**Pull request merged**
